### ISSUE TITLE
workspace

### ISSUE THREAD

**Issue by mugukamil** [shuvalov-anton/code-screenshots#35]
привет) незнаю куда писать. может сделаешь тоже самое только фото рабочего окружения(стол, клава и тд)?:)

**Comment by shuvalov-anton** [comment]
Я — пас)

**Comment by mugukamil** [comment]
![Okey](http://i1.kym-cdn.com/photos/images/original/000/082/456/Okay.png)

**Comment by shuvalov-anton** [comment]
Но ведь ты можешь сделать это сам. Например как общий блог на medium

**Comment by mugukamil** [comment]
я в вебе - ноль

**Comment by shuvalov-anton** [comment]
http://medium.com/
